name: Water Data Importer
description: Flask app to import water consumption data to InfluxDB
slug: water-data-importer
version: 1.0.4
stable: true
maintainer: Codrin
url: https://github.com/codrinh/qa-to-ha-influxdb
documentation: https://github.com/codrinh/qa-to-ha-influxdb
repository: https://github.com/codrinh/qa-to-ha-influxdb
issues: https://github.com/codrinh/qa-to-ha-influxdb/issues
homeassistant: 2026.2.1
image: ghcr.io/codrinh/water-data-importer-{arch}

arch:
  - amd64
  - aarch64

ports:
  "5000/tcp": 5000

options:
  influx_host: homeassistant.local
  influx_port: 8086
  influx_db: homeassistant
  influx_user: homeassistant
  influx_password: homeassistant
  flask_port: 5000

schema:
  influx_host: str
  influx_port: int
  influx_db: str
  influx_user: str
  influx_password: str
  flask_port: int


boot: auto
startup: services
privileged: false

environment:
  PYTHONUNBUFFERED: 1

panel_title: Water Data Importer
panel_admin: true
