name: Water Data Importer
description: Flask app to import water consumption data to InfluxDB
slug: water-data-importer
version: 1.0.1
stable: true
maintainers:
  - Codrin
url: https://github.com/codrinh/qa-to-ha-influxdb
documentation: https://github.com/codrinh/qa-to-ha-influxdb
repository: https://github.com/codrinh/qa-to-ha-influxdb
issues: https://github.com/codrinh/qa-to-ha-influxdb/issues
homeassistant: 2024.1.0
image: ghcr.io/codrinh/water-data-importer-{arch}

arch:
  - amd64
  - aarch64

ports:
  5000/tcp: 5000

options:
  influx_host: influxdb.local
  influx_port: 8086
  influx_db: homeassistant
  influx_user: admin
  influx_password: admin123
  flask_port: 5000

schema:
  influx_host: str
  influx_port: int
  influx_db: str
  influx_user: str
  influx_password: str
  flask_port: int

services:
  influxdb:
    publish: true

boot: auto
startup: services
privileged:
  - CAP_SYS_ADMIN

environment:
  PYTHONUNBUFFERED: 1

panel_title: Water Data Importer
panel_admin: true
